name: Create candiate zip

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  create_artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Create archive
        run: |
          mv CANDIDATE_README.md README.md
          rm -rf .*
          
      - name: Upload archive
        uses: actions/upload-artifact@v4
        with:
          name: azure_paired_programming_exercise
          path: ./